[package]
name = "esp-testrun"
version = "0.1.0"
edition = "2021"

[dependencies]
espflash = { version = "2.0", default-features = false }
serialport = { version = "4.2.2" }
clap = { version = "4.3.0", features = ["derive"] }
log = { version = "0.4.20" }
pretty_env_logger = { version = "0.5.0" }
